name = "zor-proxy-worker"
main = "src/index.ts"
compatibility_date = "2026-08-30"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSIONS"
id = "a7462b9e44c241fe830333d45cb1954c"

[vars]
STARKNET_RPC_URL = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/alch_-87xFRsdib2F_f-o2GBMV"
STRK20_CONTRACT_ADDRESS = "0x0254a6b2997ef52e9f830ce1f543f6b29768295e8d17e2267d672c552cfe0d91"
PROXY_WALLET_ADDRESS = "0x6bac485e95d541c9d3e5bed098b47d143a6a8a9e51d62b4e3ba31249d9700bd"
PRICE_PER_MINUTE = "0.001"
ALLOWED_ORIGIN = "*"

[env.production]
STARKNET_RPC_URL = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/alch_-87xFRsdib2F_f-o2GBMV"
ALLOWED_ORIGIN = "https://zor-proxy.pages.dev"
